add check csv-header to githubCI

diff --git a/.github/workflows/smoke-tests.yml b/.github/workflows/smoke-tests.yml
--- a/.github/workflows/smoke-tests.yml
+++ b/.github/workflows/smoke-tests.yml
@@ -49,5 +49,17 @@ jobs:
       if: failure()
       run: exit 1
 
+    - name: Check header in first line
+      run: |
+        HEADER="repository name,author name,author login,author email,date and time,changed files,commit id,branch"
+        FIRST_LINE=$(head -n 1 out.csv)
+
+        if [[ "$FIRST_LINE" == "$HEADER"* ]]; then
+          echo "Header is valid"
+        else
+          echo "Header is invalid"
+          exit 1
+        fi
+
     - name: Show out.csv
       run: cat out.csv
